### ISSUE TITLE
Not working and would love to use it

### ISSUE THREAD

**Issue by TophC7** [GabrielTenma/lightdm-gab-gradient#3]
Hi I just installed the theme however its not really working. The themes does not load the user at all no profile picture or way to login into the user; it just shows the default 'Magic Wave' Text and trying out my password does nothing.

I kinda expect it not to work since I'm in Solus and kinda had to install the entirety of web-greeter manually, including dependencies, but if the default theme works there should be a way to make your awesome theme work too!! I'd love to use it.

**Comment by GabrielTenma** [comment]
sorry this theme is no longer supported
work correctly for single user
